import { prisma } from "../src/lib/db";

const seedTrends = [
  // US trends
  {
    slug: "phantom-step-challenge",
    title: "Phantom Step Challenge",
    description: "A footwork illusion creating the effect of gliding backward while moving forward. 340% growth in 72 hours among 18-24 demographic.",
    category: "Dance",
    country: "US",
    growthRate: 340,
    views: "48M",
    creators: 12500,
    thumbnail: "https://images.unsplash.com/photo-1535525153412-5a42439a210d?w=600&h=800&fit=crop",
    isViral: true,
    isNew: true,
    velocity: 92,
    saturation: 22,
    creatorFit: 78,
    engagement: 89,
    avgViews: "3.8M",
    competition: "LOW",
    viralScore: 92,
    opportunityScore: 88,
    whyItBlowsUp: "Visual illusion format is inherently shareable. Low production barrier means rapid creator adoption.",
    peakExpected: "48-72 hours",
    urgency: "HIGH",
    actionTime: "Upload within 24h for maximum reach",
    suggestedTitle: "I tried the Phantom Step and it actually works",
    creatorsUploaded: 12500,
    aiScore: 88,
    aiPrediction: "Will peak in 48-72 hours, then rapidly saturate. Dance niche should adopt immediately.",
    tags: ["PhantomStep", "DanceChallenge", "Viral"],
  },
  {
    slug: "ai-voice-clone-filter",
    title: "AI Voice Clone Filter",
    description: "Creators are using real-time voice cloning to duet themselves as celebrities. Audio engagement up 520% on videos using this technique.",
    category: "Tech",
    country: "US",
    growthRate: 520,
    views: "92M",
    creators: 8400,
    thumbnail: "https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=600&h=800&fit=crop",
    isViral: true,
    isNew: true,
    velocity: 96,
    saturation: 15,
    creatorFit: 65,
    engagement: 94,
    avgViews: "11M",
    competition: "MEDIUM",
    viralScore: 96,
    opportunityScore: 94,
    whyItBlowsUp: "Novelty of AI voice cloning creates immediate curiosity. Celebrity impressions drive comment engagement.",
    peakExpected: "5-7 days",
    urgency: "MEDIUM",
    actionTime: "5-7 day window before barrier to entry rises",
    suggestedTitle: "AI cloned my voice and I can't tell the difference",
    creatorsUploaded: 8400,
    aiScore: 94,
    aiPrediction: "High barrier to entry limits saturation. Tech and comedy niches have 5-7 day window.",
    tags: ["AIVoice", "VoiceClone", "TechTrend"],
  },
  {
    slug: "seamless-object-transitions",
    title: "Seamless Object Transitions",
    description: "Throw any object at the camera and cut to a completely different scene. The smoother the catch, the more viral the video.",
    category: "Editing",
    country: "US",
    growthRate: 210,
    views: "31M",
    creators: 6700,
    thumbnail: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&h=800&fit=crop",
    isViral: false,
    isNew: true,
    velocity: 74,
    saturation: 35,
    creatorFit: 82,
    engagement: 76,
    avgViews: "4.6M",
    competition: "MEDIUM",
    viralScore: 74,
    opportunityScore: 76,
    whyItBlowsUp: "Satisfying visual payoff rewards full watch time. Editing skill barrier limits copycats.",
    peakExpected: "2 weeks",
    urgency: "LOW",
    actionTime: "Steady growth for 2 weeks",
    suggestedTitle: "The smoothest transition you'll see today",
    creatorsUploaded: 6700,
    aiScore: 76,
    aiPrediction: "Steady growth for 2 weeks. Editing-heavy format favors established creators.",
    tags: ["Transitions", "Editing", "Cinematic"],
  },
  {
    slug: "5am-routine-aesthetic",
    title: "5AM Routine Aesthetic",
    description: "Hyper-stylized morning routines with ASMR levels of audio production. Watch time 3.2x higher than standard vlogs.",
    category: "Lifestyle",
    country: "US",
    growthRate: 180,
    views: "27M",
    creators: 4100,
    thumbnail: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=800&fit=crop",
    isViral: false,
    isNew: false,
    velocity: 58,
    saturation: 68,
    creatorFit: 90,
    engagement: 62,
    avgViews: "6.6M",
    competition: "HIGH",
    viralScore: 58,
    opportunityScore: 62,
    whyItBlowsUp: "Aspirational content drives saves and shares. High production value creates sub-niche barriers.",
    peakExpected: "Saturated",
    urgency: "LOW",
    actionTime: "Differentiate through unique angle or location",
    suggestedTitle: "My realistic 5AM routine (no sugar coating)",
    creatorsUploaded: 4100,
    aiScore: 62,
    aiPrediction: "Saturated but stable. Differentiation through unique location or profession is key.",
    tags: ["5AMRoutine", "Productivity", "Aesthetic"],
  },
  {
    slug: "miniature-diy-crafting-us",
    title: "Miniature World Building",
    description: "Creating entire rooms and worlds at 1:12 scale. Average session duration 4m 32s — highest in DIY category.",
    category: "DIY",
    country: "US",
    growthRate: 195,
    views: "33M",
    creators: 5600,
    thumbnail: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=600&h=800&fit=crop",
    isViral: false,
    isNew: true,
    velocity: 70,
    saturation: 28,
    creatorFit: 60,
    engagement: 78,
    avgViews: "5.9M",
    competition: "MEDIUM",
    viralScore: 72,
    opportunityScore: 78,
    whyItBlowsUp: "Extremely high session duration signals algorithm boost. Satisfying process drives replays.",
    peakExpected: "2 weeks",
    urgency: "MEDIUM",
    actionTime: "Start building now — process takes time",
    suggestedTitle: "I built a tiny kitchen that actually works",
    creatorsUploaded: 5600,
    aiScore: 78,
    aiPrediction: "Steady growth with high retention. Long-form potential on YouTube Shorts.",
    tags: ["Miniature", "DIY", "Crafting"],
  },
  {
    slug: "silent-reaction-duets",
    title: "Silent Reaction Duets",
    description: "Reacting to videos with only facial expressions — no audio commentary. Paradoxically driving higher completion rates.",
    category: "Entertainment",
    country: "US",
    growthRate: 220,
    views: "41M",
    creators: 9800,
    thumbnail: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop",
    isViral: false,
    isNew: false,
    velocity: 82,
    saturation: 55,
    creatorFit: 85,
    engagement: 81,
    avgViews: "4.2M",
    competition: "HIGH",
    viralScore: 76,
    opportunityScore: 81,
    whyItBlowsUp: "Silence creates curiosity gap. No language barrier = global reach. Easy to produce.",
    peakExpected: "1 week",
    urgency: "HIGH",
    actionTime: "Jump on now before saturation peaks",
    suggestedTitle: "Reacting without saying a single word",
    creatorsUploaded: 9800,
    aiScore: 81,
    aiPrediction: "High saturation risk but universal format. Comedy and reaction channels should adopt immediately.",
    tags: ["Reaction", "Duet", "Silent"],
  },
  // Japan trends
  {
    slug: "deconstructed-food-asmr-jp",
    title: "Deconstructed Food ASMR",
    description: "Breaking down food into its molecular components with satisfying audio. New sub-niche exploding in Japan and Korea.",
    category: "Food",
    country: "JP",
    growthRate: 290,
    views: "56M",
    creators: 3200,
    thumbnail: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=800&fit=crop",
    isViral: true,
    isNew: false,
    velocity: 85,
    saturation: 18,
    creatorFit: 55,
    engagement: 84,
    avgViews: "17.5M",
    competition: "LOW",
    viralScore: 85,
    opportunityScore: 84,
    whyItBlowsUp: "Cross-cultural appeal. ASMR satisfies algorithmic watch time requirements. Low creator count = blue ocean.",
    peakExpected: "10 days",
    urgency: "HIGH",
    actionTime: "10-day first-mover advantage for Western creators",
    suggestedTitle: "Deconstructing a strawberry into molecules",
    creatorsUploaded: 3200,
    aiScore: 84,
    aiPrediction: "Crossing into Western markets now. Food and science creators have 10-day first-mover advantage.",
    tags: ["FoodASMR", "Deconstructed", "Satisfying"],
  },
  {
    slug: "tokyo-street-interviews",
    title: "Tokyo Street Interviews",
    description: "Asking strangers philosophical questions in neon-lit Tokyo streets. Authentic reactions driving 4.5% engagement rate.",
    category: "Social",
    country: "JP",
    growthRate: 155,
    views: "19M",
    creators: 890,
    thumbnail: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=800&fit=crop",
    isViral: false,
    isNew: false,
    velocity: 62,
    saturation: 12,
    creatorFit: 70,
    engagement: 72,
    avgViews: "21.3M",
    competition: "LOW",
    viralScore: 68,
    opportunityScore: 72,
    whyItBlowsUp: "Authentic unscripted content outperforms polished videos. Location-based novelty drives shares.",
    peakExpected: "3 weeks",
    urgency: "MEDIUM",
    actionTime: "Replicable in any major city",
    suggestedTitle: "I asked strangers in Tokyo about happiness",
    creatorsUploaded: 890,
    aiScore: 72,
    aiPrediction: "Niche but loyal audience. Geographic replication potential is high.",
    tags: ["StreetInterview", "Tokyo", "Philosophy"],
  },
  {
    slug: "calligraphy-dance-fusion",
    title: "Calligraphy Dance Fusion",
    description: "Combining traditional Japanese calligraphy strokes with contemporary dance moves. 280% growth among arts community.",
    category: "Dance",
    country: "JP",
    growthRate: 280,
    views: "34M",
    creators: 2100,
    thumbnail: "https://images.unsplash.com/photo-1528164344705-47542687000d?w=600&h=800&fit=crop",
    isViral: true,
    isNew: true,
    velocity: 78,
    saturation: 10,
    creatorFit: 45,
    engagement: 86,
    avgViews: "16.2M",
    competition: "LOW",
    viralScore: 82,
    opportunityScore: 86,
    whyItBlowsUp: "Cultural authenticity meets modern expression. Appeals to both Japanese and international audiences.",
    peakExpected: "2 weeks",
    urgency: "HIGH",
    actionTime: "Limited competition window — adopt cultural elements",
    suggestedTitle: "When calligraphy meets hip hop",
    creatorsUploaded: 2100,
    aiScore: 86,
    aiPrediction: "High cultural export potential. Arts and education niches have 2-week first-mover advantage.",
    tags: ["ShodoDance", "JapaneseArt", "Fusion"],
  },
  // UK trends
  {
    slug: "british-humor-skits",
    title: "Dry British Humor Skits",
    description: "30-second skits featuring deadpan British humor. Average share rate 4.8x higher than US comedy content in UK markets.",
    category: "Entertainment",
    country: "GB",
    growthRate: 195,
    views: "28M",
    creators: 4500,
    thumbnail: "https://images.unsplash.com/photo-1514306191717-452ec28c3f39?w=600&h=800&fit=crop",
    isViral: false,
    isNew: true,
    velocity: 68,
    saturation: 32,
    creatorFit: 75,
    engagement: 79,
    avgViews: "6.2M",
    competition: "MEDIUM",
    viralScore: 71,
    opportunityScore: 79,
    whyItBlowsUp: "Cultural humor creates strong regional identity. High share rate within UK demographic.",
    peakExpected: "3 weeks",
    urgency: "MEDIUM",
    actionTime: "Perfect for UK-based comedy creators",
    suggestedTitle: "British problems in 30 seconds",
    creatorsUploaded: 4500,
    aiScore: 79,
    aiPrediction: "Regional lock-in effect. UK comedy creators should adopt within 3 weeks.",
    tags: ["BritishHumor", "DryComedy", "Skits"],
  },
  {
    slug: "london-street-style",
    title: "London Street Style Ratings",
    description: "Rating passerby outfits with brutal honesty in London neighborhoods. Comment engagement 5.2x above fashion average.",
    category: "Lifestyle",
    country: "GB",
    growthRate: 240,
    views: "22M",
    creators: 1800,
    thumbnail: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&h=800&fit=crop",
    isViral: true,
    isNew: false,
    velocity: 74,
    saturation: 18,
    creatorFit: 65,
    engagement: 82,
    avgViews: "12.2M",
    competition: "LOW",
    viralScore: 78,
    opportunityScore: 82,
    whyItBlowsUp: "Controversial ratings drive comments. Fashion content with personality outperforms polished lookbooks.",
    peakExpected: "2 weeks",
    urgency: "HIGH",
    actionTime: "Start rating outfits in your city now",
    suggestedTitle: "Rating London outfits with zero mercy",
    creatorsUploaded: 1800,
    aiScore: 82,
    aiPrediction: "Replicable in any major fashion city. UK and EU creators have 2-week head start.",
    tags: ["StreetStyle", "LondonFashion", "OOTD"],
  },
  // Brazil trends
  {
    slug: "brazil-funk-remix",
    title: "Funk Remix Challenges",
    description: "Creators remixing classic Brazilian funk tracks with modern electronic beats. 410% growth in Latin American markets.",
    category: "Dance",
    country: "BR",
    growthRate: 410,
    views: "67M",
    creators: 15200,
    thumbnail: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=600&h=800&fit=crop",
    isViral: true,
    isNew: true,
    velocity: 94,
    saturation: 42,
    creatorFit: 80,
    engagement: 91,
    avgViews: "4.4M",
    competition: "MEDIUM",
    viralScore: 89,
    opportunityScore: 91,
    whyItBlowsUp: "Music-driven trends have inherent viral mechanics. Brazilian funk has global crossover potential.",
    peakExpected: "1 week",
    urgency: "HIGH",
    actionTime: "Dance creators should learn the steps immediately",
    suggestedTitle: "This funk remix broke my algorithm",
    creatorsUploaded: 15200,
    aiScore: 91,
    aiPrediction: "Music trend with explosive growth. Dance and music niches should adopt within 7 days.",
    tags: ["FunkRemix", "BrazilianMusic", "DanceChallenge"],
  },
  // India trends
  {
    slug: "bollywood-transition-edits",
    title: "Bollywood Transition Edits",
    description: "Seamlessly transitioning from everyday outfits to Bollywood costumes. 360% growth among South Asian creators.",
    category: "Editing",
    country: "IN",
    growthRate: 360,
    views: "54M",
    creators: 11800,
    thumbnail: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=800&fit=crop",
    isViral: true,
    isNew: true,
    velocity: 86,
    saturation: 38,
    creatorFit: 72,
    engagement: 88,
    avgViews: "4.6M",
    competition: "MEDIUM",
    viralScore: 87,
    opportunityScore: 88,
    whyItBlowsUp: "Cultural pride meets impressive editing. Nostalgic Bollywood references drive shares across generations.",
    peakExpected: "10 days",
    urgency: "HIGH",
    actionTime: "Start practicing the transition technique now",
    suggestedTitle: "From casual to Bollywood in 3 seconds",
    creatorsUploaded: 11800,
    aiScore: 88,
    aiPrediction: "High cultural resonance with global diaspora. Editing and fashion niches have 10-day window.",
    tags: ["BollywoodEdit", "Transition", "DesiContent"],
  },
  // Germany trends
  {
    slug: "german-engineering-hacks",
    title: "Engineering Life Hacks",
    description: "Over-engineering simple daily tasks with German precision. 275% growth among tech and DIY communities.",
    category: "Tech",
    country: "DE",
    growthRate: 275,
    views: "31M",
    creators: 3400,
    thumbnail: "https://images.unsplash.com/photo-1581092921461-eab62e97a782?w=600&h=800&fit=crop",
    isViral: false,
    isNew: true,
    velocity: 72,
    saturation: 15,
    creatorFit: 68,
    engagement: 83,
    avgViews: "9.1M",
    competition: "LOW",
    viralScore: 77,
    opportunityScore: 83,
    whyItBlowsUp: "Stereotype humor combined with genuinely useful content. Appeals to engineering and maker communities globally.",
    peakExpected: "3 weeks",
    urgency: "MEDIUM",
    actionTime: "Tech creators can adopt the format immediately",
    suggestedTitle: "The most German way to organize cables",
    creatorsUploaded: 3400,
    aiScore: 83,
    aiPrediction: "Steady growth with high retention. Tech and DIY niches should adopt within 3 weeks.",
    tags: ["Engineering", "LifeHacks", "GermanTech"],
  },
  // Canada trends
  {
    slug: "wilderness-cooking-asmr",
    title: "Wilderness Cooking ASMR",
    description: "Cooking gourmet meals in remote Canadian wilderness. 310% growth among outdoor and food communities.",
    category: "Food",
    country: "CA",
    growthRate: 310,
    views: "42M",
    creators: 2900,
    thumbnail: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=600&h=800&fit=crop",
    isViral: true,
    isNew: true,
    velocity: 80,
    saturation: 12,
    creatorFit: 58,
    engagement: 87,
    avgViews: "14.5M",
    competition: "LOW",
    viralScore: 84,
    opportunityScore: 87,
    whyItBlowsUp: "Nature ASMR combined with food satisfaction. Unique setting creates differentiation from saturated food content.",
    peakExpected: "2 weeks",
    urgency: "HIGH",
    actionTime: "Outdoor creators should adopt the cooking format",
    suggestedTitle: "Cooking a full meal in the Canadian wilderness",
    creatorsUploaded: 2900,
    aiScore: 87,
    aiPrediction: "Crossover between outdoor and food niches. Canadian and Nordic creators have 2-week advantage.",
    tags: ["WildernessCooking", "ASMR", "Outdoor"],
  },
  // Australia trends
  {
    slug: "aussie-slang-challenge",
    title: "Australian Slang Translation",
    description: "Translating extreme Australian slang for international audiences. 245% growth with 6.8% engagement rate.",
    category: "Entertainment",
    country: "AU",
    growthRate: 245,
    views: "38M",
    creators: 6700,
    thumbnail: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=600&h=800&fit=crop",
    isViral: false,
    isNew: true,
    velocity: 76,
    saturation: 22,
    creatorFit: 70,
    engagement: 85,
    avgViews: "5.7M",
    competition: "LOW",
    viralScore: 79,
    opportunityScore: 85,
    whyItBlowsUp: "Language barrier humor is universally relatable. Australian identity content performs strongly internationally.",
    peakExpected: "2 weeks",
    urgency: "MEDIUM",
    actionTime: "Comedy creators can replicate with local slang",
    suggestedTitle: "Explaining Australian slang to Americans",
    creatorsUploaded: 6700,
    aiScore: 85,
    aiPrediction: "Regional humor with global appeal. Comedy creators in English-speaking markets should adopt.",
    tags: ["AussieSlang", "Translation", "Comedy"],
  },
  // France trends
  {
    slug: "french-pastry-asmr",
    title: "French Pastry Micro-ASMR",
    description: "Extreme close-up pastry techniques with amplified audio. 330% growth in food and satisfying content.",
    category: "Food",
    country: "FR",
    growthRate: 330,
    views: "45M",
    creators: 4100,
    thumbnail: "https://images.unsplash.com/photo-1555507036-ab1f4038023a?w=600&h=800&fit=crop",
    isViral: true,
    isNew: true,
    velocity: 84,
    saturation: 14,
    creatorFit: 52,
    engagement: 90,
    avgViews: "11M",
    competition: "LOW",
    viralScore: 86,
    opportunityScore: 90,
    whyItBlowsUp: "French culinary prestige combined with ASMR trends. Extremely high watch time and save rates.",
    peakExpected: "10 days",
    urgency: "HIGH",
    actionTime: "Food creators should start filming macro techniques",
    suggestedTitle: "The most satisfying croissant technique",
    creatorsUploaded: 4100,
    aiScore: 90,
    aiPrediction: "Luxury positioning in food niche. Baking and pastry creators have 10-day first-mover advantage.",
    tags: ["PastryASMR", "FrenchBaking", "Satisfying"],
  },
  // Mexico trends
  {
    slug: "midnight-street-food-tours",
    title: "Midnight Street Food Tours",
    description: "Touring Mexican street food stalls at midnight with cinematic editing. 290% growth in food and travel niches.",
    category: "Food",
    country: "MX",
    growthRate: 290,
    views: "39M",
    creators: 5600,
    thumbnail: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=800&fit=crop",
    isViral: true,
    isNew: false,
    velocity: 78,
    saturation: 28,
    creatorFit: 62,
    engagement: 86,
    avgViews: "7M",
    competition: "MEDIUM",
    viralScore: 81,
    opportunityScore: 86,
    whyItBlowsUp: "Night-time aesthetic combined with authentic food culture. Travel restrictions make this vicariously appealing.",
    peakExpected: "2 weeks",
    urgency: "MEDIUM",
    actionTime: "Food and travel creators should adopt the night tour format",
    suggestedTitle: "Mexico City street food at 2AM hits different",
    creatorsUploaded: 5600,
    aiScore: 86,
    aiPrediction: "Travel-food crossover with strong visual appeal. Latin American creators have immediate advantage.",
    tags: ["StreetFood", "Mexico", "FoodTour"],
  },
];

const seedCreators = [
  { username: "mayachen", displayName: "Maya Chen", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop", followers: 4200000, niche: "Dance" },
  { username: "alexrivera", displayName: "Alex Rivera", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop", followers: 2800000, niche: "Tech" },
  { username: "yukitanaka", displayName: "Yuki Tanaka", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop", followers: 6100000, niche: "Lifestyle" },
  { username: "jordansmith", displayName: "Jordan Smith", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop", followers: 1900000, niche: "Food" },
];

async function main() {
  console.log("[SEED] Starting...");

  for (const t of seedTrends) {
    const { tags, ...trendData } = t;

    const trend = await prisma.trend.upsert({
      where: { slug: trendData.slug },
      update: trendData,
      create: trendData,
    });

    for (const tagName of tags) {
      const tag = await prisma.tag.upsert({
        where: { name: tagName },
        update: {},
        create: { name: tagName },
      });

      await prisma.trendTag.upsert({
        where: { trendId_tagId: { trendId: trend.id, tagId: tag.id } },
        update: {},
        create: { trendId: trend.id, tagId: tag.id },
      });
    }

    console.log(`[SEED] Trend: ${trend.title}`);
  }

  for (const c of seedCreators) {
    await prisma.creator.upsert({
      where: { username: c.username },
      update: c,
      create: c,
    });
    console.log(`[SEED] Creator: ${c.displayName}`);
  }

  console.log("[SEED] Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
